# Generated by Django 6.0.3 on 2026-04-07 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seloniphile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=60)),
                ('discription', models.TextField()),
                ('link', models.CharField(max_length=80)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seloniphile.actor')),
            ],
        ),
    ]
