# Generated by Django 6.0.3 on 2026-04-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seloniphile', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='InstaUser',
        ),
    ]
