# Generated by Django 6.0.3 on 2026-04-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seloniphile', '0003_rename_user_instauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='pic',
            field=models.ImageField(default='user.png', upload_to='images/'),
        ),
    ]
