# Generated by Django 6.0.3 on 2026-04-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seloniphile', '0004_instauser_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instauser',
            name='actor',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='InstaUser',
        ),
    ]
