# Generated by Django 6.0.3 on 2026-04-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seloniphile', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='instapost',
        ),
    ]
