# Generated by Django 6.0.3 on 2026-04-15 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seloniphile', '0007_rename_post_instapost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUserd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='seloniphile.instauser')),
                ('following_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_person', to='seloniphile.instauser')),
            ],
        ),
    ]
