# Generated by Django 6.0.3 on 2026-04-23 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seloniphile', '0010_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seloniphile.instapost'),
        ),
    ]
