# Generated by Django 6.0.3 on 2026-05-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seloniphile', '0012_like_unlike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like_unlike',
            new_name='LikeUnlike',
        ),
    ]
