# Generated by Django 6.0.3 on 2026-06-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seloniphile', '0013_rename_like_unlike_likeunlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeunlike',
            unique_together={('user_fk', 'post_fk')},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seloniphile.instapost')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seloniphile.instauser')),
            ],
        ),
    ]
