# Generated by Django 6.0.2 on 2026-06-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seloniphile', '0015_createreel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_image', models.FileField(upload_to='Story_image/')),
                ('story_caption', models.TextField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seloniphile.instauser')),
            ],
        ),
    ]
