# Generated by Django 6.0.2 on 2026-06-27 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seloniphile', '0019_chatroom_user2_alter_chatroom_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senderby', to='seloniphile.instauser'),
        ),
    ]
